### ISSUE TITLE
关于shuoshuo页面问题

### ISSUE THREAD

**Issue by Chocolate1999** [Drew233/hexo-shuoshuo#1]
js渲染之后 会将自己的appID和appKEY也渲染到页面 查看源代码就能获取到

**Comment by Drew233** [comment]
这两个本来就是公开的，对本js没有影响

**Comment by Drew233** [comment]
这里用的主要是leancloud的用户系统，你在 leancloud上设置账号密码即可。记得设置权限，教程中介绍了 。

**Comment by Chocolate1999** [comment]
> 这里用的主要是leancloud的用户系统，你在 leancloud上设置账号密码即可。记得设置权限，教程中介绍了 。

ok 谢谢你的回复
